name: Rust

on:
  release:
    types: [created]
env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc]
    steps:
    - uses: actions/checkout@v2
    - name: Rust Release binary
      uses: rust-build/rust-build.action@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUSTTARGET: ${{ matrix.target }}

